### ISSUE TITLE
Install Guide for FX9860GIII/9750GIII/Graph 35+E II?

### ISSUE THREAD

**Issue by androidenthusiast101** [jeb5/Casio-Calculator-FX9860-Apps#1]
I have the latest one which does not require the FA-124 program and all you need to do is drag and drop using file explorer. How do you install the games in GM1 format and are there any more games that are compatible for my FX9860? So far I have only found a French website but most games are only compatible on the last version which was the "FX9860II".

**Comment by jeb5** [comment]
[Planéte Casio](https://www-planet--casio-com.translate.goog/Fr/programmes/trier_programmes.php?calc=3&_x_tr_sl=auto&_x_tr_tl=en&_x_tr_hl=en-GB) is probably your best bet for games, yes. 
I think everything on the site is in G1A or similar format, which is an "add-on" rather than a Casio-Basic program. Add-ons are written in C, and can do a lot more than Casio-Basic programs. You should be able to install them using FA-124.

I don't have an FX9860, so I can't give you much advice about installing via drag-and-drop, but FA-124 is compatible with your calculator, so it might just be worth trying to install software through that.
